### ISSUE TITLE
Cannot be installed on server?

### ISSUE THREAD

**Issue by JiuyeAyan** [TheAGamePlayer/The-Pure-Suffering-Mod#2]
I tried to install this mod on our server, but then our server is not able to launch
Here's the crash report:

Details:
	Mod File: PureSuffering-1.16.5-1.1.2B.jar
	Failure message: Pure Suffering (puresuffering) has failed to load correctly
		com.electronwill.nightconfig.core.io.ParsingException: Invalid value ture - Expected the boolean value true.
	Mod Version: 1.1.2B
	Mod Issue URL: https://github.com/TheAGamePlayer/The-Pure-Suffering-Mod/issues
	Exception message: com.electronwill.nightconfig.core.io.ParsingException: Invalid value ture - Expected the boolean value true.
Stacktrace:
	at com.electronwill.nightconfig.toml.ValueParser.parseTrue(ValueParser.java:175) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:46) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:68) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:101) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.3.jar:?] {}
	at dev.theagameplayer.puresuffering.config.PSConfig.loadConfig(PSConfig.java:212) ~[puresuffering:1.16.5-1.1.2B] {re:classloading}
	at dev.theagameplayer.puresuffering.config.PSConfig.initConfig(PSConfig.java:201) ~[puresuffering:1.16.5-1.1.2B] {re:classloading}
	at dev.theagameplayer.puresuffering.PureSufferingMod.createConfig(PureSufferingMod.java:39) ~[puresuffering:1.16.5-1.1.2B] {re:classloading}
	at dev.theagameplayer.puresuffering.PureSufferingMod.<init>(PureSufferingMod.java:27) ~[puresuffering:1.16.5-1.1.2B] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_221] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_221] {}

**Comment by JiuyeAyan** [comment]
oops, our client crashed too, seems not compatible with byg mod? (All The Biomes You'll Go):

Crash report:
-- Head ---- 
Thread: Render threadStacktrace: at net.minecraft.client.renderer.color.ItemColors.func_199877_a(ItemColors.java:97) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:byg.mixins.json:client.MixinItemColors,pl:mixin:A,pl:runtimedistcleaner:A} at corgiaoc.byg.client.textures.ColorManager.onItemColorsInit(ColorManager.java:30) ~[byg:1.3.4] {re:mixin,re:classloading} at net.minecraft.client.renderer.color.ItemColors.handler$zjd000$addBYGItemColors(ItemColors.java:515) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:byg.mixins.json:client.MixinItemColors,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:byg.mixins.json:client.MixinItemColors,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.<init>(Minecraft.java:461) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}-- Initialization --

**Comment by TheAGamePlayer** [comment]
As I've stated on the curse forge page, this seems to be a rendering issue between a BYG Mixin and the rendering with the eclipse skyboxes. I will contact the mod author of BYG to see if we can sort out the compatibility issue, but in the meantime I suggest you guys go to your client config and set "useSkyBoxRenderer" to false to see if this solves the problem.

**Comment by JiuyeAyan** [comment]
> The server side crash seems to be a config value being changed incorrectly, so I'd have to guess it to be a typo.
> 
> As for the client-side, that crash seems to be a rendering issue between a BYG Mixin and the rendering with the eclipse skyboxes. I will contact the mod author of BYG to see if we can sort out the compatibility issue, but in the meantime I suggest you guys go to your client config and set "useSkyBoxRenderer" to false to see if this solves the problem.

-----------------
For the server side, I deleted the config file and let MC to creat a new one, and my server was successfully initiated, thank you very much!

For the client side, I have deleted the config file and generated a new config file too and then I followed your words to modified the config but my client was still unable to initiate, it was only after I installed this mod that my MC crashed at the initiation. While when I watching my crash report, I can only understand words like renderer and byg ( I'm sorry that I don't understand furthur more)

And I found one thing, I tried to creat a clean MC version which only included [The Pure Suffering] and [BYG] these two mods, and my mc was successfully initiated. What should I do?
